# Deploy pipeline
trigger:
 batch: false
 branches:
  include:
  - master
 paths:
  exclude:
  - readme.md
stages:
 - stage: Deploy
   pool:
     vmImage: 'ubuntu-latest'
   jobs:
    - job: DeployWebAppProd
      steps:
       - task: DownloadPipelineArtifact@2
         inputs:
           buildType: 'specific'
           project: 'ab43f2c4-cbec-8f34-b6a6-b1b96af2c4bf'
           definition: '408'
           buildVersionToDownload: 'latest'
           allowPartiallySucceededBuilds: true
           allowFailedBuilds: true
           artifactName: 'app'
           targetPath: '$(Pipeline.Workspace)'
       - bash: cd $(Pipeline.Workspace); echo $(ls)
       - bash: cd $(Pipeline.Workspace)/app; echo $(ls)
       - task: AzureStaticWebApp@0
         inputs:
           cwd: '$(Pipeline.Workspace)'
           app_location: '/'
           skip_app_build: true
           skip_api_build: true
           verbose: true
         env:
           azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_WAVE_0689C6903)'